import { Config } from '../types';

export const defaultConfig: Partial<Config> = {
  subreddits: [
    'forhire',
    'hireaprogrammer',
    'reactjs',
    'WFHjobs',
    'WorkOnline',
    'WebDevJobs',
    'WebDeveloperJobs',
    'remoteworks',
    'RemoteJobseekers',
    'RemoteJobSearch',
    'RemoteJobs',
    'RemoteDevelopersIndia',
    'nextjs',
    'jobboardsearch',
    'javascriptjobs',
    'hiring',
    'FreelanceProgramming',
    'freelancing',
    'jobbit',
    'freelance',
    'remotejs',
    'jobs',
  ],
  keywords: [
    'hiring',
    'hire',
    'looking for',
    'freelance',
    'contract',
    'remote',
    'developer',
    'engineer',
    'next.js',
    'react',
    'typescript',
    'node.js',
    'full stack',
    'frontend',
    'backend',
    'devops',
  ],
  regexPatterns: [
    'looking\\s+for\\s+.*(dev|developer|engineer)',
    '(hiring|seeking)\\s+.*(dev|developer|engineer)',
    '(remote|freelance|contract)\\s+.*(position|role|job)',
  ],
  pollIntervalMs: 15000,
  maxRetries: 3,
  backoffMultiplier: 2,
  maxBackoffMs: 60000,
  geminiThreshold: 0.7,
  storeType: 'sqlite',
  sqlitePath: './data/seen_posts.db',
  userAgent:
    'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36',
  metricsEnabled: true,
  port: 3000,
  logLevel: 'info',
  logPretty: true,
};
